---
- name: Setup Jenkins Master Node
  hosts: jenkins_master
  become: yes

  vars:
    jenkins_repo_url: "https://pkg.jenkins.io/debian-stable"
    jenkins_key_url: "https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key"

  tasks:
    - name: Update apt repository cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - openjdk-11-jdk
          - wget
          - gnupg
          - curl
        state: present

    - name: Add Jenkins repository key
      ansible.builtin.apt_key:
        url: "{{ jenkins_key_url }}"
        state: present

    - name: Add Jenkins apt repository
      ansible.builtin.apt_repository:
        repo: "deb {{ jenkins_repo_url }} binary/"
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
        update_cache: yes

    - name: Enable Jenkins service
      systemd:
        name: jenkins
        enabled: yes
        state: started

    - name: Ensure Jenkins is listening on port 8080
      wait_for:
        host: 127.0.0.1
        port: 8080
        state: started
        delay: 10
        timeout: 60

    - name: Display Jenkins initial admin password
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_password
      changed_when: false

    - name: Print Jenkins initial admin password
      debug:
        msg: "Initial Jenkins admin password: {{ jenkins_password.stdout }}"
