---
- name: Setup Jenkins Worker Nodes
  hosts: jenkins_workers
  become: yes

  vars:
    jenkins_master_ip: "{{ hostvars['jenkins-master']['ansible_host'] | default(groups['jenkins_master'][0]) }}"
    agent_dir: /opt/jenkins
    agent_jar: /opt/jenkins/agent.jar
    jenkins_user: devops

  tasks:
    - name: Update apt repositories
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - openjdk-11-jdk
          - git
          - wget
          - curl
        state: present

    - name: Create Jenkins agent directory
      file:
        path: "{{ agent_dir }}"
        state: directory
        owner: "{{ jenkins_user }}"
        group: "{{ jenkins_user }}"
        mode: '0755'

    - name: Download Jenkins agent jar from master
      get_url:
        url: "http://{{ jenkins_master_ip }}:8080/jnlpJars/agent.jar"
        dest: "{{ agent_jar }}"
        mode: '0755'
      retries: 3
      delay: 10
      register: download_result
      until: download_result is succeeded

    - name: Create Jenkins agent service file
      copy:
        dest: /etc/systemd/system/jenkins-agent.service
        content: |
          [Unit]
